MvcMovie/MvcMovie/Models/Show.cs
using System.ComponentModel.DataAnnotations;

namespace MvcMovie.Models
{
    public class Show
    {
        public int Id { get; set; }

        //[Required(ErrorMessage = "Date and Time are required.")]
        [Required]
        [DataType(DataType.DateTime)]
        public DateTime DateAndTime { get; set; }

        public Movie Movie { get; set; }
        public int MovieId { get; set; }
        public int SalonId { get; set; }
        public Salon Salon { get; set; }
        
        public ICollection<Booking> Bookings { get; set; }
    }
}

MvcMovie/MvcMovie/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class BookingsController : Controller
    {
        private readonly MvcMovieContext _context;

        public BookingsController(MvcMovieContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            var mvcMovieContext = _context.Bookings.Include(b => b.Show);
            return View(await mvcMovieContext.ToListAsync());
        }

        public IActionResult Booking()
        {
            return View();
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Show)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        [HttpGet]
        public IActionResult Booking(int showId)
        {
            var totalSeats = 40;
            var bookedSeats = _context.Bookings
                .Select(b => b.SeatNr)
                .ToList();

            var availableSeats = Enumerable.Range(1, totalSeats)
                                           .Where(seat => !bookedSeats.Contains(seat))
                                           .ToList();
            ViewData["AvailableSeats"] = new SelectList(availableSeats);
            ViewData["Movies"] = new SelectList(_context.Movies, "Id", "Title");

            ViewData["Salons"] = new SelectList(_context.Salons, "Id", "SalonNr");

            var booking = new Booking { ShowId = showId };
            return View(booking);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Booking(Booking booking)
        {
            if (booking.ShowId == null || booking.ShowId == 0)
            {
                var newShow = CreateDefaultShow((int)booking.MovieId);
                _context.Shows.Add(newShow);
                await _context.SaveChangesAsync();

                booking.ShowId = newShow.Id;
            }


            if (_context.Bookings.Any(b => b.ShowId == booking.ShowId && b.SeatNr == booking.SeatNr))
            {
                ModelState.AddModelError("SeatNr", "This seat is already booked.");
                return View(booking);
            }

            booking.BookingNr = GenerateBookingNumber();
            _context.Bookings.Add(booking);
            await _context.SaveChangesAsync();

            return RedirectToAction("Confirmation", new { bookingNr = booking.BookingNr });
        }

        private Show CreateDefaultShow(int movieId)
        {
            return new Show
            {
                MovieId = movieId,
                SalonId = (int)(_context.Salons.FirstOrDefault()?.Id),
                DateAndTime = DateTime.Now
            };
        }


        private string GenerateBookingNumber()
        {
            return Guid.NewGuid().ToString().Substring(0, 8).ToUpper();
        }

        public IActionResult Confirmation(string bookingNr)
        {
            var booking = _context.Bookings
                .Include(b => b.Show)
                .ThenInclude(s => s.Movie)
                .Include(b => b.Show.Salon)
                .FirstOrDefault(b => b.BookingNr == bookingNr);

            if (booking == null)
                return NotFound();

            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings.FindAsync(id);
            if (booking == null)
            {
                return NotFound();
            }
            ViewData["ShowId"] = new SelectList(_context.Shows, "Id", "Id", booking.ShowId);
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SeatNr,BookingNr,VisitorName,VisitorEmail,ShowId")] Booking booking)
        {
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ShowId"] = new SelectList(_context.Shows, "Id", "Id", booking.ShowId);
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Bookings
                .Include(b => b.Show)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Bookings.FindAsync(id);
            if (booking != null)
            {
                _context.Bookings.Remove(booking);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BookingExists(int id)
        {
            return _context.Bookings.Any(e => e.Id == id);
        }

        [HttpGet]
        public IActionResult Find()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Find(string bookingNr)
        {
            if (string.IsNullOrEmpty(bookingNr))
            {
                ViewBag.Message = "Please enter a valid booking number.";
                return View();
            }

            var booking = _context.Bookings
                .Include(b => b.Show)
                .ThenInclude(s => s.Movie)
                .Include(b => b.Show.Salon)
                .FirstOrDefault(b => b.BookingNr == bookingNr);

            if (booking == null)
            {
                ViewBag.Message = "Booking not found. Please check your booking number.";
                return View();
            }

            return RedirectToAction("Confirmation", new { bookingNr });
        }
    }
}

MvcMovie/MvcMovie/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class ShowsController : Controller
    {
        private readonly MvcMovieContext _context;

        public ShowsController(MvcMovieContext context)
        {
            _context = context;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            var mvcMovieContext = _context.Shows.Include(s => s.Movie).Include(s => s.Salon);
            return View(await mvcMovieContext.ToListAsync());
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .Include(s => s.Movie)
                .Include(s => s.Salon)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id");
            ViewData["SalonId"] = new SelectList(_context.Salons, "Id", "Id");
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,DateAndTime,MovieId,SalonId")] Show show)
        {
            if (ModelState.IsValid)
            {
                _context.Add(show);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", show.MovieId);
            ViewData["SalonId"] = new SelectList(_context.Salons, "Id", "Id", show.SalonId);
            return View(show);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows.FindAsync(id);
            if (show == null)
            {
                return NotFound();
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", show.MovieId);
            ViewData["SalonId"] = new SelectList(_context.Salons, "Id", "Id", show.SalonId);
            return View(show);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DateAndTime,MovieId,SalonId")] Show show)
        {
            if (id != show.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(show);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowExists(show.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MovieId"] = new SelectList(_context.Movies, "Id", "Id", show.MovieId);
            ViewData["SalonId"] = new SelectList(_context.Salons, "Id", "Id", show.SalonId);
            return View(show);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var show = await _context.Shows
                .Include(s => s.Movie)
                .Include(s => s.Salon)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (show == null)
            {
                return NotFound();
            }

            return View(show);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var show = await _context.Shows.FindAsync(id);
            if (show != null)
            {
                _context.Shows.Remove(show);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowExists(int id)
        {
            return _context.Shows.Any(e => e.Id == id);
        }
    }
}

MvcMovie/MvcMovie/Views/Shows/Create.cshtml
@model MvcMovie.Models.Show

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="DateAndTime" class="control-label"></label>
                <input asp-for="DateAndTime" class="form-control" />
                <span asp-validation-for="DateAndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class ="form-control" asp-items="ViewBag.MovieId"></select>
            </div>
            <div class="form-group">
                <label asp-for="SalonId" class="control-label"></label>
                <select asp-for="SalonId" class ="form-control" asp-items="ViewBag.SalonId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie/MvcMovie/Views/Shows/Delete.cshtml
@model MvcMovie.Models.Show

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAndTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salon.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MvcMovie/MvcMovie/Views/Shows/Details.cshtml
@model MvcMovie.Models.Show

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Show</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAndTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAndTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salon.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcMovie/MvcMovie/Views/Shows/Edit.cshtml
@model MvcMovie.Models.Show

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Show</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateAndTime" class="control-label"></label>
                <input asp-for="DateAndTime" class="form-control" />
                <span asp-validation-for="DateAndTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SalonId" class="control-label"></label>
                <select asp-for="SalonId" class="form-control" asp-items="ViewBag.SalonId"></select>
                <span asp-validation-for="SalonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcMovie/MvcMovie/Views/Shows/Index.cshtml
@model IEnumerable<MvcMovie.Models.Show>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DateAndTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salon)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DateAndTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Movie.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salon.Id)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MvcMovie/MvcMovie/Views/Shows/Show.cshtml
@model IEnumerable<MvcMovie.Models.Show>

@{
    ViewData["Title"] = "Shows";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().Salon.SalonNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Movie.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().DateAndTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Salon.SalonNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Movie.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAndTime)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
                    <a asp-controller="Bookings" asp-action="Booking" asp-route-id="@item.Id">Booking</a>
                </td>
            </tr>
        }
    </tbody>
</table>